language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
 - "pypy"
before_install:
 - "sudo apt-get update -qq"
 - "sudo apt-get install -qq toilet figlet"
install:
    - "pip install -r dev-requirements.txt"
    - "pip install ."
script: python pyfiglet/test.py && pytest -vv
